//! Generated exhaustive dispositions for input STRING Osiris arguments.
//!
//! Records use the exact callable kind, name, arity, and argument index.
//! Parameter metadata is repeated and checked by the core ledger validator.
//!
//! Generated from generated_osiris_catalog.rs for source build
//! 4.1.1.7398727 (4a2ca23f02f6b5b5eed91ed07e8290c16cadf5f28032e66a19c89d6c2697eaac).

use super::osiris_catalog::{OsirisContractKind, OsirisParameterDirection};
use super::osiris_domains::{
    OsirisArgumentDisposition, OsirisArgumentDomainRecord, OsirisResourceDomain,
};

const SOURCE_VERSION: &str = "4.1.1.7398727";
const SOURCE_HASH: &str = "4a2ca23f02f6b5b5eed91ed07e8290c16cadf5f28032e66a19c89d6c2697eaac";
const GENERATOR_VERSION: &str = "bg3-ls-osiris-catalog-v1";
const REVIEWED_ON: &str = "2026-09-01";

#[rustfmt::skip]
macro_rules! resource {
    ($kind:ident, $name:literal, $arity:literal, $index:literal, $parameter:literal, $disposition:expr, $url:literal, $revision:literal) => {
        OsirisArgumentDomainRecord::resource(
            OsirisContractKind::$kind, $name, $arity, $index, $parameter, "STRING",
            OsirisParameterDirection::In, $disposition, $url, $revision, REVIEWED_ON,
            SOURCE_VERSION, SOURCE_HASH, GENERATOR_VERSION,
        )
    };
}

#[rustfmt::skip]
macro_rules! catalog {
    ($kind:ident, $name:literal, $arity:literal, $index:literal, $parameter:literal, $disposition:expr) => {
        OsirisArgumentDomainRecord::catalog_only(
            OsirisContractKind::$kind, $name, $arity, $index, $parameter, "STRING",
            OsirisParameterDirection::In, $disposition, REVIEWED_ON, SOURCE_VERSION,
            SOURCE_HASH, GENERATOR_VERSION,
        )
    };
}

/// Complete reviewed ledger for the generated catalog's 518 input strings.
#[rustfmt::skip]
pub const OSIRIS_ARGUMENT_DOMAIN_LEDGER: &[OsirisArgumentDomainRecord] = &[
    catalog!(Query, "AbilityGetDifficultyLevelMappedValue", 3, 0, "_Difficulty", OsirisArgumentDisposition::DeferredSemanticReview),
    catalog!(Call, "ActivateTrade", 6, 5, "_ItemsTagFilter", OsirisArgumentDisposition::Expression),
    catalog!(Call, "AddBackgroundGoal", 3, 2, "_CategoryId", OsirisArgumentDisposition::Enumeration),
    catalog!(Call, "AddBoosts", 4, 1, "_Boosts", OsirisArgumentDisposition::Expression),
    catalog!(Call, "AddBoosts", 4, 2, "_SourceID", OsirisArgumentDisposition::DeferredSemanticReview),
    resource!(Call, "AddCustomMaterialOverride", 2, 1, "_Preset", OsirisArgumentDisposition::DeferredResource(OsirisResourceDomain::Custom("ScriptMaterialOverridePreset")), "https://docs.baldursgate3.game/index.php?title=AddCustomMaterialOverride&oldid=3170", 3170),
    catalog!(Call, "AddCustomMaterialResourceOverride", 3, 1, "_Resource", OsirisArgumentDisposition::DeferredSemanticReview),
    catalog!(Call, "AddCustomMaterialResourceOverride", 3, 2, "_Filter", OsirisArgumentDisposition::Expression),
    catalog!(Call, "AddEntryToCustomBook", 2, 0, "_Bookname", OsirisArgumentDisposition::RuntimeIdentifier),
    catalog!(Call, "AddEntryToCustomBook", 2, 1, "_Entryname", OsirisArgumentDisposition::RuntimeIdentifier),
    catalog!(Call, "AddIllustrationToCustomBook", 2, 0, "_Bookname", OsirisArgumentDisposition::RuntimeIdentifier),
    catalog!(Call, "AddIllustrationToCustomBook", 2, 1, "_Entryname", OsirisArgumentDisposition::RuntimeIdentifier),
    resource!(Call, "AddPassive", 2, 1, "_PassiveID", OsirisArgumentDisposition::Resource(OsirisResourceDomain::PassiveData), "https://docs.baldursgate3.game/index.php?title=AddPassive&oldid=3067", 3067),
    resource!(Call, "AddSpell", 4, 1, "_Spell", OsirisArgumentDisposition::Resource(OsirisResourceDomain::SpellData), "https://docs.baldursgate3.game/index.php?title=AddSpell&oldid=2263", 2263),
    catalog!(Call, "AddTadpolePower", 3, 1, "_Power", OsirisArgumentDisposition::DeferredSemanticReview),
    catalog!(Call, "AddTrackedSoundEntity", 2, 1, "_RtpcName", OsirisArgumentDisposition::RuntimeIdentifier),
    catalog!(Event, "AddedTo", 3, 2, "_AddType", OsirisArgumentDisposition::Enumeration),
    catalog!(Event, "AnimationEvent", 3, 1, "_EventName", OsirisArgumentDisposition::RuntimeIdentifier),
    catalog!(Call, "AppearAt", 6, 4, "_AppearedEvent", OsirisArgumentDisposition::RuntimeIdentifier),
    catalog!(Call, "AppearAtPosition", 8, 6, "_AppearedEvent", OsirisArgumentDisposition::RuntimeIdentifier),
    catalog!(Call, "AppearOnTrailOutOfSightTo", 7, 5, "_AppearedEvent", OsirisArgumentDisposition::RuntimeIdentifier),
    catalog!(Call, "AppearOutOfSightTo", 7, 5, "_AppearedEvent", OsirisArgumentDisposition::RuntimeIdentifier),
    catalog!(Call, "AppearOutOfSightToPosition", 9, 7, "_AppearedEvent", OsirisArgumentDisposition::RuntimeIdentifier),
    catalog!(Event, "AppearTeleportFailed", 2, 1, "_AppearEvent", OsirisArgumentDisposition::RuntimeIdentifier),
    catalog!(Call, "ApplyDamage", 4, 2, "_DamageType", OsirisArgumentDisposition::Enumeration),
    resource!(Call, "ApplyStatus", 5, 1, "_Status", OsirisArgumentDisposition::Resource(OsirisResourceDomain::StatusData), "https://docs.baldursgate3.game/index.php?title=ApplyStatus&oldid=2246", 2246),
    catalog!(Call, "AttachHitProxy", 3, 2, "_Attachment", OsirisArgumentDisposition::Enumeration),
    catalog!(Call, "AttachSpring", 4, 1, "_AttachedBone", OsirisArgumentDisposition::RuntimeIdentifier),
    catalog!(Call, "AttachSpring", 4, 3, "_AttachToBone", OsirisArgumentDisposition::RuntimeIdentifier),
    catalog!(Event, "AttackedBy", 7, 3, "_DamageType", OsirisArgumentDisposition::Enumeration),
    catalog!(Event, "AttackedBy", 7, 5, "_DamageCause", OsirisArgumentDisposition::Enumeration),
    catalog!(Query, "CalculatePassiveSkill", 3, 1, "_TargetSkill", OsirisArgumentDisposition::Enumeration),
    catalog!(Call, "CameraActivate", 6, 1, "_Name", OsirisArgumentDisposition::DeferredSemanticReview),
    catalog!(Event, "CameraReachedNode", 5, 2, "_event", OsirisArgumentDisposition::RuntimeIdentifier),
    resource!(Query, "CanCastSpellOnEnemyInSameCombat", 3, 1, "_SpellID", OsirisArgumentDisposition::Resource(OsirisResourceDomain::SpellData), "https://docs.baldursgate3.game/index.php?title=CanCastSpellOnEnemyInSameCombat&oldid=2874", 2874),
    resource!(Query, "CanShowSpellForCharacter", 3, 1, "_SpellID", OsirisArgumentDisposition::Resource(OsirisResourceDomain::SpellData), "https://docs.baldursgate3.game/index.php?title=CanShowSpellForCharacter&oldid=2289", 2289),
    resource!(Event, "CastSpell", 5, 1, "_Spell", OsirisArgumentDisposition::Resource(OsirisResourceDomain::SpellData), "https://docs.baldursgate3.game/index.php?title=CastSpell&oldid=2271", 2271),
    catalog!(Event, "CastSpell", 5, 2, "_SpellType", OsirisArgumentDisposition::Enumeration),
    catalog!(Event, "CastSpell", 5, 3, "_SpellElement", OsirisArgumentDisposition::Enumeration),
    resource!(Event, "CastSpellFailed", 5, 1, "_Spell", OsirisArgumentDisposition::Resource(OsirisResourceDomain::SpellData), "https://docs.baldursgate3.game/index.php?title=CastSpellFailed&oldid=2273", 2273),
    catalog!(Event, "CastSpellFailed", 5, 2, "_SpellType", OsirisArgumentDisposition::Enumeration),
    catalog!(Event, "CastSpellFailed", 5, 3, "_SpellElement", OsirisArgumentDisposition::Enumeration),
    resource!(Event, "CastedSpell", 5, 1, "_Spell", OsirisArgumentDisposition::Resource(OsirisResourceDomain::SpellData), "https://docs.baldursgate3.game/index.php?title=CastedSpell&oldid=2269", 2269),
    catalog!(Event, "CastedSpell", 5, 2, "_SpellType", OsirisArgumentDisposition::Enumeration),
    catalog!(Event, "CastedSpell", 5, 3, "_SpellElement", OsirisArgumentDisposition::Enumeration),
    catalog!(Call, "CharacterDisableCrime", 2, 1, "_Crime", OsirisArgumentDisposition::RuntimeIdentifier),
    catalog!(Event, "CharacterDisarmed", 3, 2, "_SlotName", OsirisArgumentDisposition::DeferredSemanticReview),
    catalog!(Call, "CharacterEnableCrime", 2, 1, "_Crime", OsirisArgumentDisposition::RuntimeIdentifier),
    resource!(Call, "CharacterGiveEquipmentSet", 2, 1, "_EquipmentSet", OsirisArgumentDisposition::Resource(OsirisResourceDomain::Equipment), "https://docs.baldursgate3.game/index.php?title=CharacterGiveEquipmentSet&oldid=3137", 3137),
    catalog!(Query, "CharacterIsCrimeEnabled", 3, 1, "_Crime", OsirisArgumentDisposition::RuntimeIdentifier),
    catalog!(Call, "CharacterMoveTo", 5, 2, "_MovementSpeed", OsirisArgumentDisposition::Enumeration),
    catalog!(Call, "CharacterMoveTo", 5, 3, "_Event", OsirisArgumentDisposition::RuntimeIdentifier),
    catalog!(Call, "CharacterMoveToAndTalk", 6, 3, "_MoveID", OsirisArgumentDisposition::RuntimeIdentifier),
    catalog!(Call, "CharacterMoveToAndTalk", 6, 4, "_MovementSpeed", OsirisArgumentDisposition::Enumeration),
    catalog!(Call, "CharacterMoveToAndTalkFail", 4, 2, "_MoveId", OsirisArgumentDisposition::RuntimeIdentifier),
    catalog!(Call, "CharacterMoveToAndTalkFail", 4, 3, "_Reason", OsirisArgumentDisposition::DeferredSemanticReview),
    catalog!(Event, "CharacterMoveToAndTalkFailed", 4, 2, "_MoveID", OsirisArgumentDisposition::RuntimeIdentifier),
    catalog!(Event, "CharacterMoveToAndTalkFailed", 4, 3, "_FailureReason", OsirisArgumentDisposition::DeferredSemanticReview),
    catalog!(Event, "CharacterMoveToAndTalkRequestDialog", 4, 3, "_MoveID", OsirisArgumentDisposition::RuntimeIdentifier),
    catalog!(Call, "CharacterMoveToPosition", 7, 4, "_MovementSpeed", OsirisArgumentDisposition::Enumeration),
    catalog!(Call, "CharacterMoveToPosition", 7, 5, "_Event", OsirisArgumentDisposition::RuntimeIdentifier),
    catalog!(Event, "CharacterOnCrimeSensibleActionNotification", 10, 1, "_CrimeRegion", OsirisArgumentDisposition::RuntimeIdentifier),
    catalog!(Event, "CharacterOnCrimeSensibleActionNotification", 10, 3, "_PriortiyName", OsirisArgumentDisposition::RuntimeIdentifier),
    catalog!(Query, "CharacterRegisterCrime", 6, 1, "_CrimeType", OsirisArgumentDisposition::RuntimeIdentifier),
    catalog!(Query, "CharacterRegisterCrimeWithPosition", 9, 1, "_CrimeType", OsirisArgumentDisposition::RuntimeIdentifier),
    catalog!(Query, "CharacterRemoveTaggedItems", 4, 1, "_Tags", OsirisArgumentDisposition::Expression),
    catalog!(Event, "CharacterSelectedAsBestUnavailableFallbackLead", 4, 1, "_CrimeRegion", OsirisArgumentDisposition::RuntimeIdentifier),
    catalog!(Call, "CharacterStopCrime", 3, 1, "_CrimeType", OsirisArgumentDisposition::RuntimeIdentifier),
    catalog!(Event, "CharacterTagEvent", 3, 2, "_Event", OsirisArgumentDisposition::RuntimeIdentifier),
    catalog!(Query, "CheckRulesetModifierString", 3, 1, "_Value", OsirisArgumentDisposition::FreeText),
    catalog!(Call, "ClearScreenFade", 4, 2, "_FadeID", OsirisArgumentDisposition::RuntimeIdentifier),
    catalog!(Call, "ClearVarObject", 2, 1, "_VarName", OsirisArgumentDisposition::RuntimeIdentifier),
    catalog!(Call, "ClearVarUUID", 2, 1, "_VarName", OsirisArgumentDisposition::RuntimeIdentifier),
    catalog!(Call, "CloseStoryElementUI", 3, 2, "_UIInstance", OsirisArgumentDisposition::RuntimeIdentifier),
    catalog!(Call, "CloseUI", 2, 1, "_UIName", OsirisArgumentDisposition::RuntimeIdentifier),
    catalog!(Query, "Concatenate", 3, 0, "_StringA", OsirisArgumentDisposition::FreeText),
    catalog!(Query, "Concatenate", 3, 1, "_StringB", OsirisArgumentDisposition::FreeText),
    catalog!(Query, "ConcatenateGUID", 3, 0, "_String", OsirisArgumentDisposition::FreeText),
    catalog!(Query, "ConcatenateInteger", 3, 0, "_String", OsirisArgumentDisposition::FreeText),
    catalog!(Query, "ConcatenateNewLine", 3, 0, "_StringA", OsirisArgumentDisposition::FreeText),
    catalog!(Query, "ConcatenateNewLine", 3, 1, "_StringB", OsirisArgumentDisposition::FreeText),
    catalog!(Query, "ConcatenateReal", 3, 0, "_String", OsirisArgumentDisposition::FreeText),
    catalog!(Call, "ConstellationTriggerInputSocket", 4, 1, "_InputSocketName", OsirisArgumentDisposition::DeferredSemanticReview),
    catalog!(Query, "CreateAt", 8, 6, "_SpawnFinishEvent", OsirisArgumentDisposition::RuntimeIdentifier),
    catalog!(Query, "CreateAtObject", 7, 4, "_SpawnFinishEvent", OsirisArgumentDisposition::RuntimeIdentifier),
    resource!(Call, "CreateExplosion", 4, 1, "_SpellID", OsirisArgumentDisposition::Resource(OsirisResourceDomain::SpellData), "https://docs.baldursgate3.game/index.php?title=CreateExplosion&oldid=3089", 3089),
    resource!(Call, "CreateExplosionAtPosition", 6, 3, "_SpellID", OsirisArgumentDisposition::Resource(OsirisResourceDomain::SpellData), "https://docs.baldursgate3.game/index.php?title=CreateExplosionAtPosition&oldid=3091", 3091),
    catalog!(Query, "CreateOutOfSightAtDirection", 9, 7, "_SpawnFinishEvent", OsirisArgumentDisposition::RuntimeIdentifier),
    catalog!(Query, "CreateOutOfSightAtDirectionFromObject", 7, 5, "_SpawnFinishEvent", OsirisArgumentDisposition::RuntimeIdentifier),
    resource!(Call, "CreateProjectileStrikeAt", 2, 1, "_SpellID", OsirisArgumentDisposition::Resource(OsirisResourceDomain::SpellData), "https://docs.baldursgate3.game/index.php?title=CreateProjectileStrikeAt&oldid=3093", 3093),
    resource!(Call, "CreateProjectileStrikeAtPosition", 4, 3, "_SpellID", OsirisArgumentDisposition::Resource(OsirisResourceDomain::SpellData), "https://docs.baldursgate3.game/index.php?title=CreateProjectileStrikeAtPosition&oldid=3095", 3095),
    catalog!(Call, "CreatePuddle", 7, 1, "_SurfaceType", OsirisArgumentDisposition::Enumeration),
    catalog!(Call, "CreateSurface", 5, 1, "_SurfaceType", OsirisArgumentDisposition::Enumeration),
    catalog!(Call, "CreateSurfaceAtPosition", 7, 3, "_SurfaceType", OsirisArgumentDisposition::Enumeration),
    catalog!(Event, "CrimeDisabled", 2, 1, "_Crime", OsirisArgumentDisposition::RuntimeIdentifier),
    catalog!(Event, "CrimeEnabled", 2, 1, "_Crime", OsirisArgumentDisposition::RuntimeIdentifier),
    catalog!(Event, "CrimeIsRegistered", 8, 1, "_CrimeType", OsirisArgumentDisposition::RuntimeIdentifier),
    catalog!(Query, "CrimeTypeGetTension", 2, 0, "_CrimeType", OsirisArgumentDisposition::RuntimeIdentifier),
    catalog!(Query, "CrimeTypeHasProperty", 3, 0, "_DisturbanceType", OsirisArgumentDisposition::RuntimeIdentifier),
    catalog!(Event, "CustomBookUIClosed", 2, 1, "_BookName", OsirisArgumentDisposition::RuntimeIdentifier),
    catalog!(Call, "DEV_EnableAnubis", 2, 1, "_Config", OsirisArgumentDisposition::FreeText),
    catalog!(Call, "DebugBreak", 1, 0, "_Message", OsirisArgumentDisposition::FreeText),
    catalog!(Call, "DebugLog", 1, 0, "_Text", OsirisArgumentDisposition::FreeText),
    catalog!(Call, "DebugText", 2, 1, "_Text", OsirisArgumentDisposition::FreeText),
    catalog!(Call, "DeleteLevelCache", 1, 0, "_LevelName", OsirisArgumentDisposition::RuntimeIdentifier),
    catalog!(Call, "DetachSpring", 2, 1, "_AttachedBone", OsirisArgumentDisposition::RuntimeIdentifier),
    catalog!(Call, "DialogSetTeleportPartyToLevelOnEnded", 2, 1, "_Level", OsirisArgumentDisposition::RuntimeIdentifier),
    catalog!(Call, "DialogSetVariableFixedString", 3, 1, "_Variable", OsirisArgumentDisposition::RuntimeIdentifier),
    catalog!(Call, "DialogSetVariableFixedString", 3, 2, "_Value", OsirisArgumentDisposition::FreeText),
    catalog!(Call, "DialogSetVariableFixedStringForInstance", 3, 1, "_Variable", OsirisArgumentDisposition::RuntimeIdentifier),
    catalog!(Call, "DialogSetVariableFixedStringForInstance", 3, 2, "_Value", OsirisArgumentDisposition::FreeText),
    catalog!(Call, "DialogSetVariableFloat", 3, 1, "_Variable", OsirisArgumentDisposition::RuntimeIdentifier),
    catalog!(Call, "DialogSetVariableFloatForInstance", 3, 1, "_Variable", OsirisArgumentDisposition::RuntimeIdentifier),
    catalog!(Call, "DialogSetVariableInt", 3, 1, "_Variable", OsirisArgumentDisposition::RuntimeIdentifier),
    catalog!(Call, "DialogSetVariableIntForInstance", 3, 1, "_Variable", OsirisArgumentDisposition::RuntimeIdentifier),
    catalog!(Call, "DialogSetVariableString", 3, 1, "_Variable", OsirisArgumentDisposition::RuntimeIdentifier),
    catalog!(Call, "DialogSetVariableString", 3, 2, "_Value", OsirisArgumentDisposition::FreeText),
    catalog!(Call, "DialogSetVariableStringForInstance", 3, 1, "_Variable", OsirisArgumentDisposition::RuntimeIdentifier),
    catalog!(Call, "DialogSetVariableStringForInstance", 3, 2, "_Value", OsirisArgumentDisposition::FreeText),
    catalog!(Call, "DialogSetVariableTranslatedString", 3, 1, "_Variable", OsirisArgumentDisposition::RuntimeIdentifier),
    resource!(Call, "DialogSetVariableTranslatedString", 3, 2, "_StringHandleValue", OsirisArgumentDisposition::DeferredResource(OsirisResourceDomain::Localization), "https://docs.baldursgate3.game/index.php?title=SetStoryDisplayName&oldid=2144", 2144),
    catalog!(Call, "DialogSetVariableTranslatedStringForInstance", 4, 1, "_Variable", OsirisArgumentDisposition::RuntimeIdentifier),
    resource!(Call, "DialogSetVariableTranslatedStringForInstance", 4, 2, "_StringHandleValue", OsirisArgumentDisposition::DeferredResource(OsirisResourceDomain::Localization), "https://docs.baldursgate3.game/index.php?title=SetStoryDisplayName&oldid=2144", 2144),
    catalog!(Call, "DialogSetVariableTranslatedStringForInstance", 4, 3, "_ReferenceStringValue", OsirisArgumentDisposition::FreeText),
    catalog!(Call, "DisappearOutOfSightTo", 6, 2, "_MovementSpeed", OsirisArgumentDisposition::Enumeration),
    catalog!(Call, "DisappearOutOfSightTo", 6, 4, "_DisappearEvent", OsirisArgumentDisposition::RuntimeIdentifier),
    catalog!(Query, "DrawSurfaceOnPath", 6, 2, "_SurfaceType", OsirisArgumentDisposition::Enumeration),
    catalog!(Event, "DualEntityEvent", 3, 2, "_Event", OsirisArgumentDisposition::RuntimeIdentifier),
    catalog!(Call, "EndActivity", 1, 0, "_Outcome", OsirisArgumentDisposition::DeferredSemanticReview),
    catalog!(Event, "EnteredLevel", 3, 2, "_Level", OsirisArgumentDisposition::RuntimeIdentifier),
    catalog!(Event, "EntityEvent", 2, 1, "_Event", OsirisArgumentDisposition::RuntimeIdentifier),
    catalog!(Call, "EscortAddCharacter", 2, 1, "_EscortGroup", OsirisArgumentDisposition::RuntimeIdentifier),
    catalog!(Event, "EscortGroupLeaderChanged", 3, 2, "_Group", OsirisArgumentDisposition::RuntimeIdentifier),
    catalog!(Call, "EscortRemoveAll", 1, 0, "_EscortGroup", OsirisArgumentDisposition::RuntimeIdentifier),
    catalog!(Call, "EscortSetLeader", 2, 1, "_EscortGroup", OsirisArgumentDisposition::RuntimeIdentifier),
    catalog!(Call, "EscortSetLeaderPriority", 3, 1, "_EscortGroup", OsirisArgumentDisposition::RuntimeIdentifier),
    catalog!(Event, "FailedToLoadItemInPreset", 4, 2, "_Level", OsirisArgumentDisposition::RuntimeIdentifier),
    catalog!(Call, "FleeFrom", 3, 1, "_FleeFromRelationType", OsirisArgumentDisposition::Enumeration),
    catalog!(Call, "GameEndWithMovie", 1, 0, "_Movie", OsirisArgumentDisposition::DeferredSemanticReview),
    catalog!(Event, "GameModeStarted", 3, 0, "_GameMode", OsirisArgumentDisposition::DeferredSemanticReview),
    catalog!(Event, "GameOption", 2, 0, "_Key", OsirisArgumentDisposition::RuntimeIdentifier),
    catalog!(Event, "GameOption", 2, 1, "_Value", OsirisArgumentDisposition::FreeText),
    resource!(Call, "GenerateTreasure", 4, 1, "_TreasureID", OsirisArgumentDisposition::Resource(OsirisResourceDomain::TreasureTable), "https://docs.baldursgate3.game/index.php?title=GenerateTreasure&oldid=2976", 2976),
    catalog!(Query, "GetAbility", 3, 1, "_Attribute", OsirisArgumentDisposition::DeferredSemanticReview),
    resource!(Query, "GetActionResourceValuePersonal", 4, 1, "_ResourceName", OsirisArgumentDisposition::DeferredResource(OsirisResourceDomain::ActionResource), "https://docs.baldursgate3.game/index.php?title=GetActionResourceValuePersonal&oldid=3198", 3198),
    catalog!(Query, "GetByTagInInventory", 3, 0, "_Tags", OsirisArgumentDisposition::Expression),
    catalog!(Query, "GetEquippedItem", 3, 1, "_Slotname", OsirisArgumentDisposition::Enumeration),
    catalog!(Query, "GetItemByTagInInventory", 3, 0, "_Tags", OsirisArgumentDisposition::Expression),
    catalog!(Query, "GetItemByTagInPartyInventory", 3, 0, "_Tags", OsirisArgumentDisposition::Expression),
    catalog!(Query, "GetItemByTagInUserInventory", 3, 0, "_Tags", OsirisArgumentDisposition::Expression),
    catalog!(Query, "GetItemByTemplateTagInInventory", 4, 1, "_Tags", OsirisArgumentDisposition::Expression),
    catalog!(Query, "GetModuleVersion", 5, 0, "_Name", OsirisArgumentDisposition::DeferredSemanticReview),
    resource!(Query, "GetSpellFromSet", 3, 0, "_SpellSetID", OsirisArgumentDisposition::Resource(OsirisResourceDomain::SpellSet), "https://docs.baldursgate3.game/index.php?title=GetSpellFromSet&oldid=2291", 2291),
    resource!(Query, "GetStatusCurrentLifetime", 3, 1, "_StatusID", OsirisArgumentDisposition::Resource(OsirisResourceDomain::StatusData), "https://docs.baldursgate3.game/index.php?title=GetStatusCurrentLifetime&oldid=2786", 2786),
    resource!(Query, "GetStatusTurns", 3, 1, "_StatusID", OsirisArgumentDisposition::Resource(OsirisResourceDomain::StatusData), "https://docs.baldursgate3.game/index.php?title=GetStatusTurns&oldid=1721", 1721),
    resource!(Query, "GetStatusType", 2, 0, "_StatusID", OsirisArgumentDisposition::Resource(OsirisResourceDomain::StatusData), "https://docs.baldursgate3.game/index.php?title=GetStatusType&oldid=2896", 2896),
    catalog!(Query, "GetSurfaceSize", 3, 1, "_SurfaceLayer", OsirisArgumentDisposition::Enumeration),
    catalog!(Query, "GetSurfaceTurns", 3, 1, "_SurfaceLayer", OsirisArgumentDisposition::Enumeration),
    catalog!(Query, "GetSurfaceTypeIndex", 2, 0, "_Surface", OsirisArgumentDisposition::Enumeration),
    catalog!(Query, "GetVarFixedString", 3, 1, "_VarName", OsirisArgumentDisposition::RuntimeIdentifier),
    catalog!(Query, "GetVarFixedStringUUID", 3, 1, "_VarName", OsirisArgumentDisposition::RuntimeIdentifier),
    catalog!(Query, "GetVarFloat", 3, 1, "_VarName", OsirisArgumentDisposition::RuntimeIdentifier),
    catalog!(Query, "GetVarFloat3", 5, 1, "_VarName", OsirisArgumentDisposition::RuntimeIdentifier),
    catalog!(Query, "GetVarInteger", 3, 1, "_VarName", OsirisArgumentDisposition::RuntimeIdentifier),
    catalog!(Query, "GetVarObject", 3, 1, "_VarName", OsirisArgumentDisposition::RuntimeIdentifier),
    catalog!(Query, "GetVarString", 3, 1, "_VarName", OsirisArgumentDisposition::RuntimeIdentifier),
    catalog!(Query, "GetVarUUID", 3, 1, "_VarName", OsirisArgumentDisposition::RuntimeIdentifier),
    resource!(Call, "GiveInspirationPoints", 4, 2, "_OptionalReason_LocalizedTextKey", OsirisArgumentDisposition::DeferredResource(OsirisResourceDomain::Localization), "https://docs.baldursgate3.game/index.php?title=SetStoryDisplayName&oldid=2144", 2144),
    resource!(Call, "GiveInspirationPoints", 4, 3, "_OptionalDescription_LocalizedTextKey", OsirisArgumentDisposition::DeferredResource(OsirisResourceDomain::Localization), "https://docs.baldursgate3.game/index.php?title=SetStoryDisplayName&oldid=2144", 2144),
    resource!(Query, "HasActiveStatus", 3, 1, "_Status", OsirisArgumentDisposition::Resource(OsirisResourceDomain::StatusData), "https://docs.baldursgate3.game/index.php?title=HasActiveStatus&oldid=2255", 2255),
    resource!(Query, "HasActiveStatusWithGroup", 3, 1, "_StatusGroup", OsirisArgumentDisposition::DeferredResource(OsirisResourceDomain::StatusGroup), "https://docs.baldursgate3.game/index.php?title=RemoveStatusesWithGroup&oldid=2890", 2890),
    resource!(Query, "HasAppliedStatus", 3, 1, "_Status", OsirisArgumentDisposition::Resource(OsirisResourceDomain::StatusData), "https://docs.baldursgate3.game/index.php?title=HasAppliedStatus&oldid=2257", 2257),
    catalog!(Query, "HasAppliedStatusOfType", 3, 1, "_StatusType", OsirisArgumentDisposition::Enumeration),
    resource!(Query, "HasAppliedStatusWithGroup", 3, 1, "_StatusGroup", OsirisArgumentDisposition::DeferredResource(OsirisResourceDomain::StatusGroup), "https://docs.baldursgate3.game/index.php?title=RemoveStatusesWithGroup&oldid=2890", 2890),
    catalog!(Query, "HasMeleeWeaponEquipped", 3, 1, "_Mainhand_Offhand_Any", OsirisArgumentDisposition::Enumeration),
    catalog!(Query, "HasOnUse", 3, 1, "_UseAction", OsirisArgumentDisposition::DeferredSemanticReview),
    resource!(Query, "HasPassive", 3, 1, "_PassiveID", OsirisArgumentDisposition::Resource(OsirisResourceDomain::PassiveData), "https://docs.baldursgate3.game/index.php?title=HasPassive&oldid=3073", 3073),
    catalog!(Query, "HasRangedWeaponEquipped", 3, 1, "_Mainhand_Offhand_Any", OsirisArgumentDisposition::Enumeration),
    resource!(Query, "HasRecipeUnlocked", 3, 1, "_RecipeID", OsirisArgumentDisposition::DeferredResource(OsirisResourceDomain::Custom("Recipe")), "https://docs.baldursgate3.game/index.php?title=UnlockJournalRecipe&oldid=1243", 1243),
    catalog!(Query, "HasSkill", 3, 1, "_Skill", OsirisArgumentDisposition::Enumeration),
    resource!(Query, "HasSpell", 3, 1, "_Spell", OsirisArgumentDisposition::Resource(OsirisResourceDomain::SpellData), "https://docs.baldursgate3.game/index.php?title=HasSpell&oldid=2293", 2293),
    catalog!(Query, "HasTadpolePower", 3, 1, "_Power", OsirisArgumentDisposition::DeferredSemanticReview),
    catalog!(Query, "HasTaggedItem", 3, 1, "_Tags", OsirisArgumentDisposition::Expression),
    catalog!(Call, "HideActivity", 1, 0, "_ActivityId", OsirisArgumentDisposition::RuntimeIdentifier),
    catalog!(Call, "HideAllActivities", 1, 0, "_Type", OsirisArgumentDisposition::DeferredSemanticReview),
    catalog!(Call, "IgnoreCrimeInRadiusWithTags", 4, 3, "_OptionalTagExpression", OsirisArgumentDisposition::Expression),
    catalog!(Call, "IgnoreCrimesInRadiusWithTagsForDuration", 4, 2, "_OptionalTagExpression", OsirisArgumentDisposition::Expression),
    catalog!(Query, "IsCharacterCreationLevel", 2, 0, "_LevelName", OsirisArgumentDisposition::RuntimeIdentifier),
    catalog!(Query, "IsEquipmentWithProficiency", 3, 1, "_ProficiencyGroup", OsirisArgumentDisposition::Enumeration),
    catalog!(Query, "IsGameLevel", 2, 0, "_LevelName", OsirisArgumentDisposition::RuntimeIdentifier),
    resource!(Query, "IsImmuneToStatus", 4, 1, "_Status", OsirisArgumentDisposition::Resource(OsirisResourceDomain::StatusData), "https://docs.baldursgate3.game/index.php?title=IsImmuneToStatus&oldid=2164", 2164),
    resource!(Query, "IsImmuneToStatusGroup", 4, 1, "_StatusGroup", OsirisArgumentDisposition::DeferredResource(OsirisResourceDomain::StatusGroup), "https://docs.baldursgate3.game/index.php?title=RemoveStatusesWithGroup&oldid=2890", 2890),
    resource!(Query, "IsSpellActive", 3, 1, "_SpellID", OsirisArgumentDisposition::Resource(OsirisResourceDomain::SpellData), "https://docs.baldursgate3.game/index.php?title=IsSpellActive&oldid=2295", 2295),
    resource!(Query, "IsStatusFromGroup", 3, 0, "_StatusID", OsirisArgumentDisposition::Resource(OsirisResourceDomain::StatusData), "https://docs.baldursgate3.game/index.php?title=IsStatusFromGroup&oldid=2888", 2888),
    resource!(Query, "IsStatusFromGroup", 3, 1, "_StatusGroup", OsirisArgumentDisposition::DeferredResource(OsirisResourceDomain::StatusGroup), "https://docs.baldursgate3.game/index.php?title=RemoveStatusesWithGroup&oldid=2890", 2890),
    catalog!(Query, "IsSubstring", 3, 0, "_StringA", OsirisArgumentDisposition::FreeText),
    catalog!(Query, "IsSubstring", 3, 1, "_StringB", OsirisArgumentDisposition::FreeText),
    catalog!(Call, "ItemMoveTo", 6, 5, "_Event", OsirisArgumentDisposition::RuntimeIdentifier),
    catalog!(Call, "ItemMoveToPosition", 7, 6, "_Event", OsirisArgumentDisposition::RuntimeIdentifier),
    catalog!(Query, "ItemTagIsInInventory", 3, 0, "_Tags", OsirisArgumentDisposition::Expression),
    catalog!(Call, "IterateActiveObjectsInSameCombatGroup", 3, 1, "_Event", OsirisArgumentDisposition::RuntimeIdentifier),
    catalog!(Call, "IterateActiveObjectsInSameCombatGroup", 3, 2, "_CompletionEvent", OsirisArgumentDisposition::RuntimeIdentifier),
    catalog!(Call, "IterateCharacters", 2, 0, "_Event", OsirisArgumentDisposition::RuntimeIdentifier),
    catalog!(Call, "IterateCharacters", 2, 1, "_CompletionEvent", OsirisArgumentDisposition::RuntimeIdentifier),
    catalog!(Call, "IterateCharactersAround", 4, 2, "_Event", OsirisArgumentDisposition::RuntimeIdentifier),
    catalog!(Call, "IterateCharactersAround", 4, 3, "_CompletionEvent", OsirisArgumentDisposition::RuntimeIdentifier),
    catalog!(Call, "IterateHitProxies", 3, 1, "_Event", OsirisArgumentDisposition::RuntimeIdentifier),
    catalog!(Call, "IterateHitProxies", 3, 2, "_CompletionEvent", OsirisArgumentDisposition::RuntimeIdentifier),
    catalog!(Call, "IterateInventory", 3, 1, "_Event", OsirisArgumentDisposition::RuntimeIdentifier),
    catalog!(Call, "IterateInventory", 3, 2, "_CompletionEvent", OsirisArgumentDisposition::RuntimeIdentifier),
    catalog!(Call, "IterateInventoryByTag", 4, 1, "_Tags", OsirisArgumentDisposition::Expression),
    catalog!(Call, "IterateInventoryByTag", 4, 2, "_Event", OsirisArgumentDisposition::RuntimeIdentifier),
    catalog!(Call, "IterateInventoryByTag", 4, 3, "_CompletionEvent", OsirisArgumentDisposition::RuntimeIdentifier),
    catalog!(Call, "IterateInventoryByTemplate", 4, 2, "_Event", OsirisArgumentDisposition::RuntimeIdentifier),
    catalog!(Call, "IterateInventoryByTemplate", 4, 3, "_CompletionEvent", OsirisArgumentDisposition::RuntimeIdentifier),
    catalog!(Call, "IterateOriginTags", 3, 1, "_Event", OsirisArgumentDisposition::RuntimeIdentifier),
    catalog!(Call, "IterateOriginTags", 3, 2, "_FinishEvent", OsirisArgumentDisposition::RuntimeIdentifier),
    catalog!(Call, "IteratePlayerCharacters", 2, 0, "_Event", OsirisArgumentDisposition::RuntimeIdentifier),
    catalog!(Call, "IteratePlayerCharacters", 2, 1, "_CompletionEvent", OsirisArgumentDisposition::RuntimeIdentifier),
    catalog!(Call, "IterateTagsCategory", 3, 1, "_Event", OsirisArgumentDisposition::RuntimeIdentifier),
    catalog!(Call, "IterateTagsCategory", 3, 2, "_FinishEvent", OsirisArgumentDisposition::RuntimeIdentifier),
    catalog!(Call, "IterateUsers", 2, 0, "_Event", OsirisArgumentDisposition::RuntimeIdentifier),
    catalog!(Call, "IterateUsers", 2, 1, "_CompletionEvent", OsirisArgumentDisposition::RuntimeIdentifier),
    resource!(Event, "LearnedSpell", 2, 1, "_Spell", OsirisArgumentDisposition::Resource(OsirisResourceDomain::SpellData), "https://docs.baldursgate3.game/index.php?title=LearnedSpell&oldid=2275", 2275),
    catalog!(Event, "LeftLevel", 2, 1, "_Level", OsirisArgumentDisposition::RuntimeIdentifier),
    catalog!(Event, "LevelGameplayReady", 2, 0, "_LevelName", OsirisArgumentDisposition::RuntimeIdentifier),
    catalog!(Event, "LevelGameplayStarted", 2, 0, "_LevelName", OsirisArgumentDisposition::RuntimeIdentifier),
    catalog!(Event, "LevelLoaded", 1, 0, "_NewLevel", OsirisArgumentDisposition::RuntimeIdentifier),
    catalog!(Event, "LevelUnloading", 1, 0, "_Level", OsirisArgumentDisposition::RuntimeIdentifier),
    catalog!(Call, "LoadGame", 1, 0, "_Savegame", OsirisArgumentDisposition::DeferredSemanticReview),
    resource!(Call, "LoadPartyPreset", 2, 0, "_Preset", OsirisArgumentDisposition::DeferredResource(OsirisResourceDomain::Custom("PartyPreset")), "https://docs.baldursgate3.game/index.php?title=LoadPartyPreset&oldid=1191", 1191),
    catalog!(Call, "Lock", 2, 1, "_Key", OsirisArgumentDisposition::RuntimeIdentifier),
    catalog!(Call, "LockWaypoint", 2, 0, "_WaypointName", OsirisArgumentDisposition::RuntimeIdentifier),
    catalog!(Call, "MagicPocketsDestroyLocalItemsByTag", 3, 1, "_Tags", OsirisArgumentDisposition::Expression),
    catalog!(Call, "MagicPocketsDropByTag", 3, 1, "_Tags", OsirisArgumentDisposition::Expression),
    catalog!(Call, "MagicPocketsMoveToByTag", 6, 1, "_Tags", OsirisArgumentDisposition::Expression),
    catalog!(Event, "MainPerformerStarted", 2, 1, "_Event", OsirisArgumentDisposition::RuntimeIdentifier),
    catalog!(Call, "MapMarkerChangeLevel", 2, 0, "_MarkerID", OsirisArgumentDisposition::RuntimeIdentifier),
    catalog!(Call, "MapMarkerChangeLevel", 2, 1, "_NewRegionID", OsirisArgumentDisposition::RuntimeIdentifier),
    resource!(Event, "MessageBoxChoiceClosed", 3, 1, "_Message", OsirisArgumentDisposition::DeferredResource(OsirisResourceDomain::Localization), "https://docs.baldursgate3.game/index.php?title=MessageBoxClosed&oldid=1235", 1235),
    catalog!(Event, "MessageBoxChoiceClosed", 3, 2, "_ResultChoice", OsirisArgumentDisposition::DeferredSemanticReview),
    resource!(Event, "MessageBoxClosed", 2, 1, "_Message", OsirisArgumentDisposition::DeferredResource(OsirisResourceDomain::Localization), "https://docs.baldursgate3.game/index.php?title=MessageBoxClosed&oldid=1235", 1235),
    resource!(Event, "MessageBoxYesNoClosed", 3, 1, "_Message", OsirisArgumentDisposition::DeferredResource(OsirisResourceDomain::Localization), "https://docs.baldursgate3.game/index.php?title=MessageBoxYesNoClosed&oldid=1237", 1237),
    catalog!(Event, "ModuleLoadedinSavegame", 5, 0, "_Name", OsirisArgumentDisposition::RuntimeIdentifier),
    catalog!(Call, "MoveItemTo", 5, 4, "_Event", OsirisArgumentDisposition::RuntimeIdentifier),
    catalog!(Event, "MovieFinished", 1, 0, "_MovieName", OsirisArgumentDisposition::DeferredSemanticReview),
    catalog!(Call, "MoviePlay", 3, 1, "_Event", OsirisArgumentDisposition::RuntimeIdentifier),
    catalog!(Event, "MoviePlaylistFinished", 1, 0, "_MovieName", OsirisArgumentDisposition::DeferredSemanticReview),
    catalog!(Call, "MusicPlayForPeer", 2, 1, "_EventName", OsirisArgumentDisposition::RuntimeIdentifier),
    catalog!(Call, "MusicPlayGeneral", 1, 0, "_EventName", OsirisArgumentDisposition::RuntimeIdentifier),
    catalog!(Call, "MusicPlayOnCharacter", 2, 1, "_EventName", OsirisArgumentDisposition::RuntimeIdentifier),
    catalog!(Call, "ObjectQuestTimerLaunch", 5, 1, "_Timer", OsirisArgumentDisposition::RuntimeIdentifier),
    resource!(Call, "ObjectQuestTimerLaunch", 5, 2, "_LocalizedTextKey", OsirisArgumentDisposition::DeferredResource(OsirisResourceDomain::Localization), "https://docs.baldursgate3.game/index.php?title=SetStoryDisplayName&oldid=2144", 2144),
    resource!(Call, "ObjectSetTitle", 2, 1, "_LocalizedTextKey", OsirisArgumentDisposition::DeferredResource(OsirisResourceDomain::Localization), "https://docs.baldursgate3.game/index.php?title=SetStoryDisplayName&oldid=2144", 2144),
    catalog!(Call, "ObjectTimerCancel", 2, 1, "_Timer", OsirisArgumentDisposition::RuntimeIdentifier),
    catalog!(Query, "ObjectTimerExists", 3, 1, "_Timer", OsirisArgumentDisposition::RuntimeIdentifier),
    catalog!(Event, "ObjectTimerFinished", 2, 1, "_Timer", OsirisArgumentDisposition::RuntimeIdentifier),
    catalog!(Call, "ObjectTimerLaunch", 4, 1, "_Timer", OsirisArgumentDisposition::RuntimeIdentifier),
    catalog!(Event, "ObscuredStateChanged", 2, 1, "_ObscuredState", OsirisArgumentDisposition::Enumeration),
    catalog!(Event, "OnCrimeInvestigatorSwitchedState", 4, 2, "_fromState", OsirisArgumentDisposition::Enumeration),
    catalog!(Event, "OnCrimeInvestigatorSwitchedState", 4, 3, "_toState", OsirisArgumentDisposition::Enumeration),
    catalog!(Call, "OpenCustomBookUI", 2, 1, "_Bookname", OsirisArgumentDisposition::RuntimeIdentifier),
    resource!(Call, "OpenMessageBox", 2, 1, "_Message", OsirisArgumentDisposition::DeferredResource(OsirisResourceDomain::Localization), "https://docs.baldursgate3.game/index.php?title=OpenMessageBox&oldid=1233", 1233),
    catalog!(Call, "OpenMessageBoxChoice", 4, 1, "_Message", OsirisArgumentDisposition::DeferredSemanticReview),
    catalog!(Call, "OpenMessageBoxChoice", 4, 2, "_Choice_1", OsirisArgumentDisposition::DeferredSemanticReview),
    catalog!(Call, "OpenMessageBoxChoice", 4, 3, "_Choice_2", OsirisArgumentDisposition::DeferredSemanticReview),
    resource!(Call, "OpenMessageBoxYesNo", 2, 1, "_Message", OsirisArgumentDisposition::DeferredResource(OsirisResourceDomain::Localization), "https://docs.baldursgate3.game/index.php?title=OpenMessageBoxYesNo&oldid=3765", 3765),
    catalog!(Call, "OpenReferencedBookUI", 3, 1, "_Bookname", OsirisArgumentDisposition::RuntimeIdentifier),
    catalog!(Call, "OpenWaypointUI", 4, 1, "_CurrentWaypoint", OsirisArgumentDisposition::RuntimeIdentifier),
    resource!(Query, "PartyGetActionResourceValue", 3, 1, "_ResourceName", OsirisArgumentDisposition::DeferredResource(OsirisResourceDomain::ActionResource), "https://docs.baldursgate3.game/index.php?title=GetActionResourceValuePersonal&oldid=3198", 3198),
    resource!(Call, "PartyIncreaseActionResourceValue", 3, 1, "_ResourceName", OsirisArgumentDisposition::DeferredResource(OsirisResourceDomain::ActionResource), "https://docs.baldursgate3.game/index.php?title=GetActionResourceValuePersonal&oldid=3198", 3198),
    resource!(Event, "PartyPresetLoaded", 2, 0, "_PartyPreset", OsirisArgumentDisposition::DeferredResource(OsirisResourceDomain::Custom("PartyPreset")), "https://docs.baldursgate3.game/index.php?title=PartyPresetLoaded&oldid=1967", 1967),
    catalog!(Event, "PartyPresetLoaded", 2, 1, "_LevelName", OsirisArgumentDisposition::RuntimeIdentifier),
    catalog!(Query, "PartyRemoveTaggedItems", 4, 1, "_Tags", OsirisArgumentDisposition::Expression),
    catalog!(Call, "Pickup", 4, 2, "_Event", OsirisArgumentDisposition::RuntimeIdentifier),
    catalog!(Call, "PlatformMoveOnSpline", 7, 5, "_EventId", OsirisArgumentDisposition::RuntimeIdentifier),
    catalog!(Call, "PlatformMoveTo", 7, 5, "_EventId", OsirisArgumentDisposition::RuntimeIdentifier),
    catalog!(Event, "PlatformMovementCanceled", 2, 1, "_EventId", OsirisArgumentDisposition::RuntimeIdentifier),
    catalog!(Event, "PlatformMovementFinished", 2, 1, "_EventId", OsirisArgumentDisposition::RuntimeIdentifier),
    catalog!(Call, "PlayAnimation", 3, 2, "_Event", OsirisArgumentDisposition::RuntimeIdentifier),
    catalog!(Call, "PlayBeamEffect", 5, 3, "_SourceBone", OsirisArgumentDisposition::RuntimeIdentifier),
    catalog!(Call, "PlayBeamEffect", 5, 4, "_TargetBone", OsirisArgumentDisposition::RuntimeIdentifier),
    catalog!(Call, "PlayEffect", 4, 2, "_Bone", OsirisArgumentDisposition::RuntimeIdentifier),
    catalog!(Call, "PlayHUDSound", 2, 1, "_SoundEvent", OsirisArgumentDisposition::RuntimeIdentifier),
    catalog!(Query, "PlayLoopBeamEffect", 6, 3, "_SourceBone", OsirisArgumentDisposition::RuntimeIdentifier),
    catalog!(Query, "PlayLoopBeamEffect", 6, 4, "_TargetBone", OsirisArgumentDisposition::RuntimeIdentifier),
    catalog!(Query, "PlayLoopEffect", 5, 2, "_BoneName", OsirisArgumentDisposition::RuntimeIdentifier),
    catalog!(Call, "PlayMovieForDialog", 3, 2, "_NodePrefix", OsirisArgumentDisposition::RuntimeIdentifier),
    catalog!(Call, "PlaySound", 2, 1, "_SoundEvent", OsirisArgumentDisposition::RuntimeIdentifier),
    catalog!(Call, "ProgressAchievement", 3, 0, "_AchievementID", OsirisArgumentDisposition::RuntimeIdentifier),
    catalog!(Event, "PuzzleUIClosed", 3, 1, "_UIInstance", OsirisArgumentDisposition::RuntimeIdentifier),
    catalog!(Event, "PuzzleUIUsed", 5, 1, "_UIInstance", OsirisArgumentDisposition::RuntimeIdentifier),
    catalog!(Event, "PuzzleUIUsed", 5, 3, "_Command", OsirisArgumentDisposition::FreeText),
    resource!(Event, "QuestAccepted", 2, 1, "_QuestID", OsirisArgumentDisposition::DeferredResource(OsirisResourceDomain::Custom("Journal")), "https://docs.baldursgate3.game/index.php?title=Journal:_Osiris_Calls&oldid=3691", 3691),
    resource!(Call, "QuestAdd", 2, 1, "_QuestID", OsirisArgumentDisposition::DeferredResource(OsirisResourceDomain::Custom("Journal")), "https://docs.baldursgate3.game/index.php?title=Journal:_Osiris_Calls&oldid=3691", 3691),
    resource!(Call, "QuestClose", 1, 0, "_QuestID", OsirisArgumentDisposition::DeferredResource(OsirisResourceDomain::Custom("Journal")), "https://docs.baldursgate3.game/index.php?title=Journal:_Osiris_Calls&oldid=3691", 3691),
    resource!(Event, "QuestClosed", 1, 0, "_QuestID", OsirisArgumentDisposition::DeferredResource(OsirisResourceDomain::Custom("Journal")), "https://docs.baldursgate3.game/index.php?title=Journal:_Osiris_Calls&oldid=3691", 3691),
    resource!(Query, "QuestGetParent", 2, 0, "_Quest", OsirisArgumentDisposition::DeferredResource(OsirisResourceDomain::Custom("Journal")), "https://docs.baldursgate3.game/index.php?title=Journal:_Osiris_Calls&oldid=3691", 3691),
    resource!(Query, "QuestGetRewardTarget", 2, 0, "_Quest", OsirisArgumentDisposition::DeferredResource(OsirisResourceDomain::Custom("Journal")), "https://docs.baldursgate3.game/index.php?title=Journal:_Osiris_Calls&oldid=3691", 3691),
    resource!(Query, "QuestIsAccepted", 3, 1, "_Quest", OsirisArgumentDisposition::DeferredResource(OsirisResourceDomain::Custom("Journal")), "https://docs.baldursgate3.game/index.php?title=Journal:_Osiris_Calls&oldid=3691", 3691),
    resource!(Query, "QuestIsClosed", 2, 0, "_Quest", OsirisArgumentDisposition::DeferredResource(OsirisResourceDomain::Custom("Journal")), "https://docs.baldursgate3.game/index.php?title=Journal:_Osiris_Calls&oldid=3691", 3691),
    catalog!(Call, "QuestMessageHide", 1, 0, "_MessageId", OsirisArgumentDisposition::RuntimeIdentifier),
    catalog!(Call, "QuestMessageShow", 2, 0, "_MessageId", OsirisArgumentDisposition::RuntimeIdentifier),
    resource!(Call, "QuestMessageShow", 2, 1, "_LocalizedTextKey", OsirisArgumentDisposition::DeferredResource(OsirisResourceDomain::Localization), "https://docs.baldursgate3.game/index.php?title=SetStoryDisplayName&oldid=2144", 2144),
    catalog!(Call, "QuestMessageWithCounterShow", 5, 0, "_MessageId", OsirisArgumentDisposition::RuntimeIdentifier),
    resource!(Call, "QuestMessageWithCounterShow", 5, 1, "_LocalizedTextKey", OsirisArgumentDisposition::DeferredResource(OsirisResourceDomain::Localization), "https://docs.baldursgate3.game/index.php?title=SetStoryDisplayName&oldid=2144", 2144),
    resource!(Call, "QuestMessageWithCounterShow", 5, 4, "_LocalizedCountTextKey", OsirisArgumentDisposition::DeferredResource(OsirisResourceDomain::Localization), "https://docs.baldursgate3.game/index.php?title=SetStoryDisplayName&oldid=2144", 2144),
    resource!(Call, "QuestSetCategory", 2, 0, "_Quest", OsirisArgumentDisposition::DeferredResource(OsirisResourceDomain::Custom("Journal")), "https://docs.baldursgate3.game/index.php?title=Journal:_Osiris_Calls&oldid=3691", 3691),
    resource!(Call, "QuestSetCategory", 2, 1, "_CategoryID", OsirisArgumentDisposition::DeferredResource(OsirisResourceDomain::Custom("Journal")), "https://docs.baldursgate3.game/index.php?title=Journal:_Osiris_Calls&oldid=3691", 3691),
    resource!(Call, "QuestUpdate", 3, 1, "_QuestID", OsirisArgumentDisposition::DeferredResource(OsirisResourceDomain::Custom("Journal")), "https://docs.baldursgate3.game/index.php?title=Journal:_Osiris_Calls&oldid=3691", 3691),
    resource!(Call, "QuestUpdate", 3, 2, "_StateID", OsirisArgumentDisposition::DeferredResource(OsirisResourceDomain::Custom("Journal")), "https://docs.baldursgate3.game/index.php?title=Journal:_Osiris_Calls&oldid=3691", 3691),
    resource!(Query, "QuestUpdateExists", 3, 0, "_QuestID", OsirisArgumentDisposition::DeferredResource(OsirisResourceDomain::Custom("Journal")), "https://docs.baldursgate3.game/index.php?title=Journal:_Osiris_Calls&oldid=3691", 3691),
    resource!(Query, "QuestUpdateExists", 3, 1, "_StateID", OsirisArgumentDisposition::DeferredResource(OsirisResourceDomain::Custom("Journal")), "https://docs.baldursgate3.game/index.php?title=Journal:_Osiris_Calls&oldid=3691", 3691),
    resource!(Query, "QuestUpdateGetTopLevel", 3, 0, "_QuestID", OsirisArgumentDisposition::DeferredResource(OsirisResourceDomain::Custom("Journal")), "https://docs.baldursgate3.game/index.php?title=Journal:_Osiris_Calls&oldid=3691", 3691),
    resource!(Query, "QuestUpdateGetTopLevel", 3, 1, "_StateID", OsirisArgumentDisposition::DeferredResource(OsirisResourceDomain::Custom("Journal")), "https://docs.baldursgate3.game/index.php?title=Journal:_Osiris_Calls&oldid=3691", 3691),
    resource!(Query, "QuestUpdateIsUnlocked", 4, 1, "_Quest", OsirisArgumentDisposition::DeferredResource(OsirisResourceDomain::Custom("Journal")), "https://docs.baldursgate3.game/index.php?title=Journal:_Osiris_Calls&oldid=3691", 3691),
    resource!(Query, "QuestUpdateIsUnlocked", 4, 2, "_Update", OsirisArgumentDisposition::DeferredResource(OsirisResourceDomain::Custom("Journal")), "https://docs.baldursgate3.game/index.php?title=Journal:_Osiris_Calls&oldid=3691", 3691),
    catalog!(Call, "QuestUpdateMessageCounter", 2, 0, "_MessageId", OsirisArgumentDisposition::RuntimeIdentifier),
    resource!(Event, "QuestUpdateUnlocked", 3, 1, "_TopLevelQuestID", OsirisArgumentDisposition::DeferredResource(OsirisResourceDomain::Custom("Journal")), "https://docs.baldursgate3.game/index.php?title=Journal:_Osiris_Calls&oldid=3691", 3691),
    resource!(Event, "QuestUpdateUnlocked", 3, 2, "_StateID", OsirisArgumentDisposition::DeferredResource(OsirisResourceDomain::Custom("Journal")), "https://docs.baldursgate3.game/index.php?title=Journal:_Osiris_Calls&oldid=3691", 3691),
    resource!(Event, "RandomCastProcessed", 5, 2, "_SpellID", OsirisArgumentDisposition::Resource(OsirisResourceDomain::SpellData), "https://docs.baldursgate3.game/index.php?title=RandomCastProcessed&oldid=2497", 2497),
    resource!(Event, "ReactionInterruptAdded", 2, 1, "_ReactionInterruptName", OsirisArgumentDisposition::Resource(OsirisResourceDomain::InterruptData), "https://docs.baldursgate3.game/index.php?title=ReactionInterruptAdded&oldid=2575", 2575),
    resource!(Event, "ReactionInterruptUsed", 3, 1, "_ReactionInterruptPrototypeId", OsirisArgumentDisposition::Resource(OsirisResourceDomain::InterruptData), "https://docs.baldursgate3.game/index.php?title=ReactionInterruptUsed&oldid=2573", 2573),
    catalog!(Call, "ReadyCheckCancel", 1, 0, "_EventId", OsirisArgumentDisposition::RuntimeIdentifier),
    catalog!(Event, "ReadyCheckFailed", 1, 0, "_Id", OsirisArgumentDisposition::RuntimeIdentifier),
    catalog!(Call, "ReadyCheckGlobal", 4, 0, "_EventId", OsirisArgumentDisposition::RuntimeIdentifier),
    resource!(Call, "ReadyCheckGlobal", 4, 1, "_TranslationId", OsirisArgumentDisposition::DeferredResource(OsirisResourceDomain::Localization), "https://docs.baldursgate3.game/index.php?title=ReadyCheckGlobal&oldid=1299", 1299),
    catalog!(Event, "ReadyCheckPassed", 1, 0, "_Id", OsirisArgumentDisposition::RuntimeIdentifier),
    catalog!(Call, "ReadyCheckSpecific", 7, 0, "_EventId", OsirisArgumentDisposition::RuntimeIdentifier),
    resource!(Call, "ReadyCheckSpecific", 7, 1, "_TranslationId", OsirisArgumentDisposition::DeferredResource(OsirisResourceDomain::Localization), "https://docs.baldursgate3.game/index.php?title=ReadyCheckSpecific&oldid=1301", 1301),
    catalog!(Call, "RealtimeObjectTimerCancel", 2, 1, "_Timer", OsirisArgumentDisposition::RuntimeIdentifier),
    catalog!(Call, "RealtimeObjectTimerLaunch", 3, 1, "_Timer", OsirisArgumentDisposition::RuntimeIdentifier),
    catalog!(Call, "RegisterWaypoint", 2, 0, "_WaypointName", OsirisArgumentDisposition::RuntimeIdentifier),
    catalog!(Call, "RemoveBoosts", 5, 1, "_Boosts", OsirisArgumentDisposition::Expression),
    catalog!(Call, "RemoveBoosts", 5, 3, "_SourceID", OsirisArgumentDisposition::RuntimeIdentifier),
    resource!(Call, "RemoveCustomMaterialOverride", 2, 1, "_Preset", OsirisArgumentDisposition::DeferredResource(OsirisResourceDomain::Custom("ScriptMaterialOverridePreset")), "https://docs.baldursgate3.game/index.php?title=RemoveCustomMaterialOverride&oldid=3172", 3172),
    catalog!(Call, "RemoveCustomMaterialResourceOverride", 2, 1, "_Resource", OsirisArgumentDisposition::DeferredSemanticReview),
    catalog!(Call, "RemoveEntryFromCustomBook", 2, 0, "_Bookname", OsirisArgumentDisposition::RuntimeIdentifier),
    catalog!(Call, "RemoveEntryFromCustomBook", 2, 1, "_Entryname", OsirisArgumentDisposition::RuntimeIdentifier),
    catalog!(Call, "RemoveIllustrationFromCustomBook", 2, 0, "_Bookname", OsirisArgumentDisposition::RuntimeIdentifier),
    catalog!(Call, "RemoveIllustrationFromCustomBook", 2, 1, "_Entryname", OsirisArgumentDisposition::RuntimeIdentifier),
    resource!(Call, "RemovePassive", 2, 1, "_PassiveID", OsirisArgumentDisposition::Resource(OsirisResourceDomain::PassiveData), "https://docs.baldursgate3.game/index.php?title=RemovePassive&oldid=3069", 3069),
    resource!(Call, "RemoveSpell", 3, 1, "_Spell", OsirisArgumentDisposition::Resource(OsirisResourceDomain::SpellData), "https://docs.baldursgate3.game/index.php?title=RemoveSpell&oldid=2265", 2265),
    resource!(Call, "RemoveStatus", 3, 1, "_Status", OsirisArgumentDisposition::Resource(OsirisResourceDomain::StatusData), "https://docs.baldursgate3.game/index.php?title=RemoveStatus&oldid=2249", 2249),
    resource!(Call, "RemoveStatusesWithGroup", 3, 1, "_StatusGroup", OsirisArgumentDisposition::DeferredResource(OsirisResourceDomain::StatusGroup), "https://docs.baldursgate3.game/index.php?title=RemoveStatusesWithGroup&oldid=2890", 2890),
    catalog!(Call, "RemoveStatusesWithType", 3, 1, "_StatusType", OsirisArgumentDisposition::Enumeration),
    catalog!(Call, "RemoveSurfaceLayer", 3, 1, "_SurfaceLayer", OsirisArgumentDisposition::Enumeration),
    catalog!(Call, "RemoveSurfaceLayerAtPosition", 5, 3, "_SurfaceLayer", OsirisArgumentDisposition::Enumeration),
    catalog!(Call, "RequestActiveRoll", 7, 2, "_RollType", OsirisArgumentDisposition::Enumeration),
    catalog!(Call, "RequestActiveRoll", 7, 3, "_SkillOrAbility", OsirisArgumentDisposition::Enumeration),
    catalog!(Call, "RequestActiveRoll", 7, 6, "_Event", OsirisArgumentDisposition::RuntimeIdentifier),
    catalog!(Call, "RequestActiveRollVersusSkill", 8, 2, "_RollType", OsirisArgumentDisposition::Enumeration),
    catalog!(Call, "RequestActiveRollVersusSkill", 8, 3, "_RollerSkillOrAbility", OsirisArgumentDisposition::Enumeration),
    catalog!(Call, "RequestActiveRollVersusSkill", 8, 4, "_SubjectSkillOrAbility", OsirisArgumentDisposition::Enumeration),
    catalog!(Call, "RequestActiveRollVersusSkill", 8, 7, "_Event", OsirisArgumentDisposition::RuntimeIdentifier),
    resource!(Call, "RequestLongRestDeny", 1, 0, "_LocalizedTextKey", OsirisArgumentDisposition::DeferredResource(OsirisResourceDomain::Localization), "https://docs.baldursgate3.game/index.php?title=SetStoryDisplayName&oldid=2144", 2144),
    catalog!(Call, "RequestModalTutorial", 2, 1, "_TutorialID", OsirisArgumentDisposition::DeferredSemanticReview),
    catalog!(Call, "RequestPassiveRoll", 7, 2, "_RollType", OsirisArgumentDisposition::Enumeration),
    catalog!(Call, "RequestPassiveRoll", 7, 3, "_SkillOrAbility", OsirisArgumentDisposition::Enumeration),
    catalog!(Call, "RequestPassiveRoll", 7, 6, "_Event", OsirisArgumentDisposition::RuntimeIdentifier),
    catalog!(Call, "RequestPassiveRollVersusSkill", 8, 2, "_RollType", OsirisArgumentDisposition::Enumeration),
    catalog!(Call, "RequestPassiveRollVersusSkill", 8, 3, "_RollerSkillOrAbility", OsirisArgumentDisposition::Enumeration),
    catalog!(Call, "RequestPassiveRollVersusSkill", 8, 4, "_SubjectSkillOrAbility", OsirisArgumentDisposition::Enumeration),
    catalog!(Call, "RequestPassiveRollVersusSkill", 8, 7, "_Event", OsirisArgumentDisposition::RuntimeIdentifier),
    resource!(Call, "RequestSetBaseArchetype", 2, 1, "_Archetype", OsirisArgumentDisposition::DeferredResource(OsirisResourceDomain::Custom("Archetype")), "https://docs.baldursgate3.game/index.php?title=RequestSetBaseArchetype&oldid=2829", 2829),
    catalog!(Call, "RequestSetSwarmGroup", 2, 1, "_SwarmGroup", OsirisArgumentDisposition::RuntimeIdentifier),
    catalog!(Event, "RequestTrade", 4, 3, "_ItemsTagFilter", OsirisArgumentDisposition::Expression),
    resource!(Query, "ResolveTranslatedString", 2, 0, "_TranslatedStringKey", OsirisArgumentDisposition::DeferredResource(OsirisResourceDomain::Localization), "https://docs.baldursgate3.game/index.php?title=SetStoryDisplayName&oldid=2144", 2144),
    catalog!(Event, "RollResult", 6, 0, "_EventName", OsirisArgumentDisposition::RuntimeIdentifier),
    catalog!(Event, "RulesetModifierChangedString", 3, 1, "_Old", OsirisArgumentDisposition::FreeText),
    catalog!(Event, "RulesetModifierChangedString", 3, 2, "_New", OsirisArgumentDisposition::FreeText),
    catalog!(Query, "SatisfiesTagExpression", 3, 1, "_TagExpression", OsirisArgumentDisposition::Expression),
    catalog!(Event, "ScreenFadeCleared", 2, 1, "_FadeID", OsirisArgumentDisposition::RuntimeIdentifier),
    catalog!(Event, "ScreenFadeDone", 2, 1, "_FadeID", OsirisArgumentDisposition::RuntimeIdentifier),
    catalog!(Call, "ScreenFadeTo", 4, 3, "_FadeID", OsirisArgumentDisposition::RuntimeIdentifier),
    catalog!(Call, "SendArenaCameraEvent", 3, 2, "_Event", OsirisArgumentDisposition::RuntimeIdentifier),
    catalog!(Call, "SendArenaNotification", 3, 1, "_StringParam", OsirisArgumentDisposition::FreeText),
    catalog!(Call, "SetAchievementProgress", 2, 0, "_AchievementID", OsirisArgumentDisposition::RuntimeIdentifier),
    catalog!(Call, "SetAchievementProgressForPlayer", 3, 0, "_AchievementID", OsirisArgumentDisposition::RuntimeIdentifier),
    catalog!(Call, "SetAnimationEvent", 2, 1, "_EventName", OsirisArgumentDisposition::RuntimeIdentifier),
    catalog!(Call, "SetAnimationEventInt", 3, 1, "_EventName", OsirisArgumentDisposition::RuntimeIdentifier),
    catalog!(Call, "SetCombatGroupAndEnterCombat", 3, 1, "_GroupID", OsirisArgumentDisposition::RuntimeIdentifier),
    catalog!(Call, "SetCombatGroupID", 2, 1, "_GroupID", OsirisArgumentDisposition::RuntimeIdentifier),
    resource!(Call, "SetCustomTradeTreasure", 2, 1, "_Treasure", OsirisArgumentDisposition::Resource(OsirisResourceDomain::TreasureTable), "https://docs.baldursgate3.game/index.php?title=SetCustomTradeTreasure&oldid=1007", 1007),
    catalog!(Call, "SetDualEntityEvent", 4, 2, "_Event", OsirisArgumentDisposition::RuntimeIdentifier),
    catalog!(Call, "SetDualEntityEventDialog", 5, 2, "_Event", OsirisArgumentDisposition::RuntimeIdentifier),
    catalog!(Call, "SetDualEntityEventReal", 5, 2, "_Event", OsirisArgumentDisposition::RuntimeIdentifier),
    catalog!(Call, "SetEditionForCustomBook", 2, 0, "_Bookname", OsirisArgumentDisposition::RuntimeIdentifier),
    catalog!(Call, "SetEntityEvent", 3, 1, "_Event", OsirisArgumentDisposition::RuntimeIdentifier),
    catalog!(Call, "SetEntityEventDialog", 4, 1, "_Event", OsirisArgumentDisposition::RuntimeIdentifier),
    catalog!(Call, "SetEntityEventGuid", 4, 1, "_Event", OsirisArgumentDisposition::RuntimeIdentifier),
    catalog!(Call, "SetEntityEventReal", 4, 1, "_Event", OsirisArgumentDisposition::RuntimeIdentifier),
    catalog!(Call, "SetHitpoints", 3, 2, "_HealTypes", OsirisArgumentDisposition::Enumeration),
    catalog!(Call, "SetHitpointsPercentage", 3, 2, "_HealTypes", OsirisArgumentDisposition::Enumeration),
    catalog!(Call, "SetReactionPriority", 3, 1, "_Reaction", OsirisArgumentDisposition::DeferredSemanticReview),
    resource!(Call, "SetStoryDisplayName", 2, 1, "_LocalizedTextKey", OsirisArgumentDisposition::DeferredResource(OsirisResourceDomain::Localization), "https://docs.baldursgate3.game/index.php?title=SetStoryDisplayName&oldid=2144", 2144),
    catalog!(Call, "SetStoryShortRestDisabled", 2, 1, "_Reason", OsirisArgumentDisposition::DeferredSemanticReview),
    resource!(Call, "SetSubRegionName", 3, 1, "_SubRegionID", OsirisArgumentDisposition::DeferredResource(OsirisResourceDomain::Localization), "https://docs.baldursgate3.game/index.php?title=SetSubRegionName&oldid=1475", 1475),
    catalog!(Call, "SetVarFixedString", 3, 1, "_VarName", OsirisArgumentDisposition::RuntimeIdentifier),
    catalog!(Call, "SetVarFixedString", 3, 2, "_VarValue", OsirisArgumentDisposition::FreeText),
    catalog!(Call, "SetVarFloat", 3, 1, "_VarName", OsirisArgumentDisposition::RuntimeIdentifier),
    catalog!(Call, "SetVarFloat3", 5, 1, "_VarName", OsirisArgumentDisposition::RuntimeIdentifier),
    catalog!(Call, "SetVarInteger", 3, 1, "_VarName", OsirisArgumentDisposition::RuntimeIdentifier),
    catalog!(Call, "SetVarObject", 3, 1, "_VarName", OsirisArgumentDisposition::RuntimeIdentifier),
    catalog!(Call, "SetVarString", 3, 1, "_VarName", OsirisArgumentDisposition::RuntimeIdentifier),
    catalog!(Call, "SetVarString", 3, 2, "_VarValue", OsirisArgumentDisposition::FreeText),
    catalog!(Call, "SetVarUUID", 3, 1, "_VarName", OsirisArgumentDisposition::RuntimeIdentifier),
    catalog!(Event, "ShapeshiftChanged", 4, 1, "_Race", OsirisArgumentDisposition::Enumeration),
    catalog!(Event, "ShapeshiftChanged", 4, 2, "_Gender", OsirisArgumentDisposition::DeferredSemanticReview),
    resource!(Event, "ShapeshiftChanged", 4, 3, "_ShapeshiftStatus", OsirisArgumentDisposition::Resource(OsirisResourceDomain::StatusData), "https://docs.baldursgate3.game/index.php?title=ShapeshiftChanged&oldid=1998", 1998),
    catalog!(Call, "ShowActivity", 1, 0, "_ActivityId", OsirisArgumentDisposition::RuntimeIdentifier),
    catalog!(Call, "ShowAllActivities", 1, 0, "_Type", OsirisArgumentDisposition::DeferredSemanticReview),
    catalog!(Call, "ShowError", 2, 1, "_Error", OsirisArgumentDisposition::Enumeration),
    resource!(Call, "ShowGameOverMenu", 1, 0, "_Reason", OsirisArgumentDisposition::DeferredResource(OsirisResourceDomain::Localization), "https://docs.baldursgate3.game/index.php?title=ShowGameOverMenu&oldid=934", 934),
    catalog!(Call, "ShowMapMarker", 3, 1, "_MarkerID", OsirisArgumentDisposition::RuntimeIdentifier),
    catalog!(Call, "ShowNotification", 2, 1, "_Text", OsirisArgumentDisposition::FreeText),
    catalog!(Call, "ShowStoryElementUI", 3, 2, "_UIInstance", OsirisArgumentDisposition::RuntimeIdentifier),
    catalog!(Call, "SonyRealtimeMultiplayerEvent", 2, 1, "_EventName", OsirisArgumentDisposition::RuntimeIdentifier),
    resource!(Query, "SpellHasSpellFlag", 3, 0, "_SpellID", OsirisArgumentDisposition::Resource(OsirisResourceDomain::SpellData), "https://docs.baldursgate3.game/index.php?title=SpellHasSpellFlag&oldid=2297", 2297),
    catalog!(Query, "SpellHasSpellFlag", 3, 1, "_SpellFlag", OsirisArgumentDisposition::Enumeration),
    catalog!(Call, "StartActivity", 1, 0, "_ActivityId", OsirisArgumentDisposition::RuntimeIdentifier),
    resource!(Event, "StartedPreviewingSpell", 4, 1, "_Spell", OsirisArgumentDisposition::Resource(OsirisResourceDomain::SpellData), "https://docs.baldursgate3.game/index.php?title=StartedPreviewingSpell&oldid=2277", 2277),
    resource!(Query, "StatStringGetCountInMagicPockets", 3, 0, "_StatName", OsirisArgumentDisposition::DeferredResource(OsirisResourceDomain::Custom("ItemStats")), "https://docs.baldursgate3.game/index.php?title=StatStringGetCountInMagicPockets&oldid=2243", 2243),
    resource!(Query, "StatStringIsInInventory", 3, 0, "_StatName", OsirisArgumentDisposition::DeferredResource(OsirisResourceDomain::Custom("ItemStats")), "https://docs.baldursgate3.game/index.php?title=StatStringIsInInventoryOf&oldid=1605", 1605),
    resource!(Event, "StatusApplied", 4, 1, "_Status", OsirisArgumentDisposition::Resource(OsirisResourceDomain::StatusData), "https://docs.baldursgate3.game/index.php?title=StatusApplied&oldid=2010", 2010),
    resource!(Event, "StatusAttempt", 4, 1, "_Status", OsirisArgumentDisposition::Resource(OsirisResourceDomain::StatusData), "https://docs.baldursgate3.game/index.php?title=StatusAttempt&oldid=2012", 2012),
    resource!(Event, "StatusAttemptFailed", 4, 1, "_Status", OsirisArgumentDisposition::Resource(OsirisResourceDomain::StatusData), "https://docs.baldursgate3.game/index.php?title=StatusAttemptFailed&oldid=2253", 2253),
    resource!(Event, "StatusRemoved", 4, 1, "_Status", OsirisArgumentDisposition::Resource(OsirisResourceDomain::StatusData), "https://docs.baldursgate3.game/index.php?title=StatusRemoved&oldid=2014", 2014),
    resource!(Call, "StopAllEffectsWithName", 2, 1, "_FxName", OsirisArgumentDisposition::DeferredResource(OsirisResourceDomain::Custom("EffectResource")), "https://docs.baldursgate3.game/index.php?title=StopAllEffectsWithName&oldid=1501", 1501),
    resource!(Event, "SubQuestUpdateUnlocked", 3, 1, "_SubQuestID", OsirisArgumentDisposition::DeferredResource(OsirisResourceDomain::Custom("Journal")), "https://docs.baldursgate3.game/index.php?title=Journal:_Osiris_Calls&oldid=3691", 3691),
    resource!(Event, "SubQuestUpdateUnlocked", 3, 2, "_StateID", OsirisArgumentDisposition::DeferredResource(OsirisResourceDomain::Custom("Journal")), "https://docs.baldursgate3.game/index.php?title=Journal:_Osiris_Calls&oldid=3691", 3691),
    catalog!(Query, "Substring", 4, 0, "_String", OsirisArgumentDisposition::FreeText),
    catalog!(Event, "SwarmAIGroupJoined", 2, 1, "_Group", OsirisArgumentDisposition::RuntimeIdentifier),
    catalog!(Event, "SwarmAIGroupLeft", 2, 1, "_Group", OsirisArgumentDisposition::RuntimeIdentifier),
    catalog!(Syscall, "SysActivateGoal", 1, 0, "_GoalTitle", OsirisArgumentDisposition::DeferredSemanticReview),
    catalog!(Syscall, "SysClear", 2, 0, "_Predicate", OsirisArgumentDisposition::Expression),
    catalog!(Syscall, "SysCompleteGoal", 1, 0, "_GoalTitle", OsirisArgumentDisposition::DeferredSemanticReview),
    catalog!(Sysquery, "SysCount", 3, 0, "_Predicate", OsirisArgumentDisposition::Expression),
    catalog!(Sysquery, "SysFactAtIndex", 4, 0, "_Predicate", OsirisArgumentDisposition::Expression),
    catalog!(Sysquery, "SysFactAtIndex", 4, 3, "_OutPredicate", OsirisArgumentDisposition::Expression),
    catalog!(Sysquery, "SysIsActive", 1, 0, "_GoalTitle", OsirisArgumentDisposition::DeferredSemanticReview),
    catalog!(Sysquery, "SysIsCompleted", 1, 0, "_GoalTitle", OsirisArgumentDisposition::DeferredSemanticReview),
    catalog!(Sysquery, "SysIsSleeping", 1, 0, "_GoalTitle", OsirisArgumentDisposition::DeferredSemanticReview),
    catalog!(Syscall, "SysLog", 2, 0, "_Predicate", OsirisArgumentDisposition::Expression),
    catalog!(Syscall, "SysSetGoalSleeping", 1, 0, "_GoalTitle", OsirisArgumentDisposition::DeferredSemanticReview),
    catalog!(Sysquery, "SysStatus", 2, 0, "_GoalTitle", OsirisArgumentDisposition::DeferredSemanticReview),
    catalog!(Sysquery, "SysWasActive", 1, 0, "_GoalTitle", OsirisArgumentDisposition::DeferredSemanticReview),
    catalog!(Sysquery, "SysWasCompleted", 1, 0, "_GoalTitle", OsirisArgumentDisposition::DeferredSemanticReview),
    catalog!(Sysquery, "SysWasDefined", 1, 0, "_GoalTitle", OsirisArgumentDisposition::DeferredSemanticReview),
    catalog!(Sysquery, "SysWasSleeping", 1, 0, "_GoalTitle", OsirisArgumentDisposition::DeferredSemanticReview),
    catalog!(Event, "TadpolePowerAssigned", 2, 1, "_Power", OsirisArgumentDisposition::DeferredSemanticReview),
    catalog!(Event, "TagEvent", 2, 1, "_Event", OsirisArgumentDisposition::RuntimeIdentifier),
    catalog!(Query, "TaggedItemsGetCountInMagicPockets", 3, 0, "_Tags", OsirisArgumentDisposition::Expression),
    catalog!(Call, "TeleportPartiesToLevelWithMovie", 3, 0, "_LevelName", OsirisArgumentDisposition::RuntimeIdentifier),
    catalog!(Call, "TeleportPartiesToLevelWithMovie", 3, 1, "_Event", OsirisArgumentDisposition::RuntimeIdentifier),
    catalog!(Call, "TeleportPartiesToLevelWithMovie", 3, 2, "_Movie", OsirisArgumentDisposition::DeferredSemanticReview),
    catalog!(Call, "TeleportPartiesWithMovie", 3, 1, "_Event", OsirisArgumentDisposition::RuntimeIdentifier),
    catalog!(Call, "TeleportPartiesWithMovie", 3, 2, "_Movie", OsirisArgumentDisposition::DeferredSemanticReview),
    catalog!(Call, "TeleportTo", 8, 2, "_Event", OsirisArgumentDisposition::RuntimeIdentifier),
    catalog!(Call, "TeleportToPosition", 10, 4, "_Event", OsirisArgumentDisposition::RuntimeIdentifier),
    resource!(Event, "Teleported", 9, 8, "_Spell", OsirisArgumentDisposition::DeferredResource(OsirisResourceDomain::SpellData), "https://docs.baldursgate3.game/index.php?title=Teleported&oldid=1041", 1041),
    catalog!(Event, "TemplateAddedTo", 4, 3, "_AddType", OsirisArgumentDisposition::Enumeration),
    catalog!(Event, "TextEvent", 1, 0, "_Event", OsirisArgumentDisposition::RuntimeIdentifier),
    catalog!(Call, "TimerCancel", 1, 0, "_Timer", OsirisArgumentDisposition::RuntimeIdentifier),
    catalog!(Query, "TimerExists", 2, 0, "_Timer", OsirisArgumentDisposition::RuntimeIdentifier),
    catalog!(Event, "TimerFinished", 1, 0, "_Timer", OsirisArgumentDisposition::RuntimeIdentifier),
    catalog!(Call, "TimerLaunch", 2, 0, "_Timer", OsirisArgumentDisposition::RuntimeIdentifier),
    catalog!(Call, "TimerPause", 1, 0, "_Timer", OsirisArgumentDisposition::RuntimeIdentifier),
    catalog!(Call, "TimerUnpause", 1, 0, "_Timer", OsirisArgumentDisposition::RuntimeIdentifier),
    resource!(Call, "TogglePassive", 2, 1, "_PassiveID", OsirisArgumentDisposition::Resource(OsirisResourceDomain::PassiveData), "https://docs.baldursgate3.game/index.php?title=TogglePassive&oldid=3071", 3071),
    catalog!(Call, "TrackAnalyticsInfo", 3, 0, "_EventName", OsirisArgumentDisposition::RuntimeIdentifier),
    catalog!(Call, "TrackAnalyticsInfo", 3, 1, "_EventData", OsirisArgumentDisposition::FreeText),
    catalog!(Call, "TransformSurface", 6, 1, "_TransformType", OsirisArgumentDisposition::Enumeration),
    catalog!(Call, "TransformSurface", 6, 2, "_TransformLayer", OsirisArgumentDisposition::Enumeration),
    catalog!(Call, "TransformSurfaceAtPosition", 8, 3, "_TransformType", OsirisArgumentDisposition::Enumeration),
    catalog!(Call, "TransformSurfaceAtPosition", 8, 4, "_TransformLayer", OsirisArgumentDisposition::Enumeration),
    catalog!(Call, "TriggerLaunchIterator", 3, 1, "_Event", OsirisArgumentDisposition::RuntimeIdentifier),
    catalog!(Call, "TriggerLaunchIterator", 3, 2, "_CompletionEvent", OsirisArgumentDisposition::RuntimeIdentifier),
    catalog!(Call, "TriggerMovieEndFadeIn", 2, 1, "_MovieName", OsirisArgumentDisposition::DeferredSemanticReview),
    resource!(Call, "TriggerSetAtmosphere", 2, 1, "_AtmosphereUUID", OsirisArgumentDisposition::DeferredResource(OsirisResourceDomain::Custom("Atmosphere")), "https://docs.baldursgate3.game/index.php?title=TriggerSetAtmosphere&oldid=3101", 3101),
    catalog!(Call, "TriggerSetLighting", 2, 1, "_LightingUUID", OsirisArgumentDisposition::DeferredSemanticReview),
    catalog!(Call, "TriggerSetSoundRTPC", 4, 1, "_Name", OsirisArgumentDisposition::RuntimeIdentifier),
    catalog!(Call, "TriggerSetSoundState", 4, 1, "_StateGroup", OsirisArgumentDisposition::RuntimeIdentifier),
    catalog!(Call, "TriggerSetSoundState", 4, 2, "_State", OsirisArgumentDisposition::RuntimeIdentifier),
    catalog!(Call, "TurnBasedTimerCancel", 2, 1, "_Timer", OsirisArgumentDisposition::RuntimeIdentifier),
    catalog!(Call, "TurnBasedTimerLaunch", 4, 1, "_Timer", OsirisArgumentDisposition::RuntimeIdentifier),
    resource!(Call, "TurnBasedTimerLaunch", 4, 2, "_LocalizedTextKey", OsirisArgumentDisposition::DeferredResource(OsirisResourceDomain::Localization), "https://docs.baldursgate3.game/index.php?title=SetStoryDisplayName&oldid=2144", 2144),
    catalog!(Event, "TutorialBoxClosed", 2, 1, "_Message", OsirisArgumentDisposition::DeferredSemanticReview),
    catalog!(Call, "UnlockAchievement", 2, 0, "_AchievementID", OsirisArgumentDisposition::RuntimeIdentifier),
    resource!(Call, "UnlockJournalRecipe", 1, 0, "_RecipeID", OsirisArgumentDisposition::DeferredResource(OsirisResourceDomain::Custom("Recipe")), "https://docs.baldursgate3.game/index.php?title=UnlockJournalRecipe&oldid=1243", 1243),
    resource!(Call, "UnlockRecipe", 3, 1, "_RecipeID", OsirisArgumentDisposition::DeferredResource(OsirisResourceDomain::Custom("Recipe")), "https://docs.baldursgate3.game/index.php?title=UnlockJournalRecipe&oldid=1243", 1243),
    catalog!(Call, "UnlockWaypoint", 3, 0, "_WaypointName", OsirisArgumentDisposition::RuntimeIdentifier),
    resource!(Event, "UnlockedRecipe", 2, 1, "_Recipe", OsirisArgumentDisposition::DeferredResource(OsirisResourceDomain::Custom("Recipe")), "https://docs.baldursgate3.game/index.php?title=UnlockJournalRecipe&oldid=1243", 1243),
    catalog!(Call, "Use", 5, 4, "_Event", OsirisArgumentDisposition::RuntimeIdentifier),
    resource!(Call, "UseSpell", 5, 1, "_SpellID", OsirisArgumentDisposition::Resource(OsirisResourceDomain::SpellData), "https://docs.baldursgate3.game/index.php?title=UseSpell&oldid=2261", 2261),
    resource!(Call, "UseSpellAtPosition", 6, 1, "_SpellID", OsirisArgumentDisposition::Resource(OsirisResourceDomain::SpellData), "https://docs.baldursgate3.game/index.php?title=UseSpellAtPosition&oldid=2267", 2267),
    catalog!(Event, "UserConnected", 3, 1, "_UserName", OsirisArgumentDisposition::RuntimeIdentifier),
    catalog!(Event, "UserConnected", 3, 2, "_UserProfileID", OsirisArgumentDisposition::RuntimeIdentifier),
    catalog!(Event, "UserDisconnected", 3, 1, "_UserName", OsirisArgumentDisposition::RuntimeIdentifier),
    catalog!(Event, "UserDisconnected", 3, 2, "_UserProfileID", OsirisArgumentDisposition::RuntimeIdentifier),
    catalog!(Event, "UserEvent", 2, 1, "_UserEvent", OsirisArgumentDisposition::RuntimeIdentifier),
    catalog!(Query, "UserRemoveTaggedItems", 4, 1, "_Tags", OsirisArgumentDisposition::Expression),
    catalog!(Query, "UserTransferTaggedItems", 5, 2, "_Tags", OsirisArgumentDisposition::Expression),
    resource!(Event, "UsingSpell", 5, 1, "_Spell", OsirisArgumentDisposition::Resource(OsirisResourceDomain::SpellData), "https://docs.baldursgate3.game/index.php?title=UsingSpell&oldid=2279", 2279),
    catalog!(Event, "UsingSpell", 5, 2, "_SpellType", OsirisArgumentDisposition::Enumeration),
    catalog!(Event, "UsingSpell", 5, 3, "_SpellElement", OsirisArgumentDisposition::Enumeration),
    resource!(Event, "UsingSpellAtPosition", 8, 4, "_Spell", OsirisArgumentDisposition::Resource(OsirisResourceDomain::SpellData), "https://docs.baldursgate3.game/index.php?title=UsingSpellAtPosition&oldid=2281", 2281),
    catalog!(Event, "UsingSpellAtPosition", 8, 5, "_SpellType", OsirisArgumentDisposition::Enumeration),
    catalog!(Event, "UsingSpellAtPosition", 8, 6, "_SpellElement", OsirisArgumentDisposition::Enumeration),
    resource!(Event, "UsingSpellInTrigger", 6, 1, "_Spell", OsirisArgumentDisposition::Resource(OsirisResourceDomain::SpellData), "https://docs.baldursgate3.game/index.php?title=UsingSpellInTrigger&oldid=2283", 2283),
    catalog!(Event, "UsingSpellInTrigger", 6, 2, "_SpellType", OsirisArgumentDisposition::Enumeration),
    catalog!(Event, "UsingSpellInTrigger", 6, 3, "_SpellElement", OsirisArgumentDisposition::Enumeration),
    resource!(Event, "UsingSpellOnTarget", 6, 2, "_Spell", OsirisArgumentDisposition::Resource(OsirisResourceDomain::SpellData), "https://docs.baldursgate3.game/index.php?title=UsingSpellOnTarget&oldid=2285", 2285),
    catalog!(Event, "UsingSpellOnTarget", 6, 3, "_SpellType", OsirisArgumentDisposition::Enumeration),
    catalog!(Event, "UsingSpellOnTarget", 6, 4, "_SpellElement", OsirisArgumentDisposition::Enumeration),
    resource!(Event, "UsingSpellOnZoneWithTarget", 6, 2, "_Spell", OsirisArgumentDisposition::Resource(OsirisResourceDomain::SpellData), "https://docs.baldursgate3.game/index.php?title=UsingSpellOnZoneWithTarget&oldid=2453", 2453),
    catalog!(Event, "UsingSpellOnZoneWithTarget", 6, 3, "_SpellType", OsirisArgumentDisposition::Enumeration),
    catalog!(Event, "UsingSpellOnZoneWithTarget", 6, 4, "_SpellElement", OsirisArgumentDisposition::Enumeration),
];

#[cfg(test)]
pub const OSIRIS_ARGUMENT_DOMAIN_LEDGER_COUNT: usize = 518;
#[cfg(test)]
pub const OSIRIS_ARGUMENT_DOMAIN_RESOURCE_COUNT: usize = 48;
#[cfg(test)]
pub const OSIRIS_ARGUMENT_DOMAIN_DEFERRED_RESOURCE_COUNT: usize = 66;
#[cfg(test)]
pub const OSIRIS_ARGUMENT_DOMAIN_ENUMERATION_COUNT: usize = 67;
#[cfg(test)]
pub const OSIRIS_ARGUMENT_DOMAIN_EXPRESSION_COUNT: usize = 29;
#[cfg(test)]
pub const OSIRIS_ARGUMENT_DOMAIN_RUNTIME_IDENTIFIER_COUNT: usize = 232;
#[cfg(test)]
pub const OSIRIS_ARGUMENT_DOMAIN_FREE_TEXT_COUNT: usize = 29;
#[cfg(test)]
pub const OSIRIS_ARGUMENT_DOMAIN_DEFERRED_REVIEW_COUNT: usize = 47;

#[cfg(test)]
mod tests {
    use super::*;
    use crate::osiris_catalog::OSIRIS_CONTRACTS;
    use crate::osiris_domains::validate_osiris_argument_domains_complete;

    #[test]
    fn ledger_is_complete_and_exactly_counted() {
        assert_eq!(
            OSIRIS_ARGUMENT_DOMAIN_LEDGER.len(),
            OSIRIS_ARGUMENT_DOMAIN_LEDGER_COUNT
        );
        validate_osiris_argument_domains_complete(OSIRIS_CONTRACTS, OSIRIS_ARGUMENT_DOMAIN_LEDGER)
            .expect("every input STRING has one exact ledger record");
    }

    #[test]
    fn ledger_disposition_totals_are_exact() {
        let count = |predicate: fn(OsirisArgumentDisposition) -> bool| {
            OSIRIS_ARGUMENT_DOMAIN_LEDGER
                .iter()
                .filter(|record| predicate(record.disposition))
                .count()
        };

        assert_eq!(
            count(|d| matches!(d, OsirisArgumentDisposition::Resource(_))),
            OSIRIS_ARGUMENT_DOMAIN_RESOURCE_COUNT
        );
        assert_eq!(
            count(|d| matches!(d, OsirisArgumentDisposition::DeferredResource(_))),
            OSIRIS_ARGUMENT_DOMAIN_DEFERRED_RESOURCE_COUNT
        );
        assert_eq!(
            count(|d| matches!(d, OsirisArgumentDisposition::Enumeration)),
            OSIRIS_ARGUMENT_DOMAIN_ENUMERATION_COUNT
        );
        assert_eq!(
            count(|d| matches!(d, OsirisArgumentDisposition::Expression)),
            OSIRIS_ARGUMENT_DOMAIN_EXPRESSION_COUNT
        );
        assert_eq!(
            count(|d| matches!(d, OsirisArgumentDisposition::RuntimeIdentifier)),
            OSIRIS_ARGUMENT_DOMAIN_RUNTIME_IDENTIFIER_COUNT
        );
        assert_eq!(
            count(|d| matches!(d, OsirisArgumentDisposition::FreeText)),
            OSIRIS_ARGUMENT_DOMAIN_FREE_TEXT_COUNT
        );
        assert_eq!(
            count(|d| matches!(d, OsirisArgumentDisposition::DeferredSemanticReview)),
            OSIRIS_ARGUMENT_DOMAIN_DEFERRED_REVIEW_COUNT
        );
    }
}
